spring:
  application:
    name: discoveryServer
server:
  port: 8761
eureka:
  server:
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 2000
  client:
    registerWithEureka: false
    fetchRegistry: false
  serviceUrl:
    defaultZone: http://localhost:8761/eureka/
