server:
  port: 8500
spring:
  graphql:
    graphiql:
      enabled: true
      path: /playground
  application:
    name: users
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/flourimus_common
    username: root
    password: password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    healthCheckUrlPath: /actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
